# Postgres DB

development:
  encoding: unicode
  adapter: postgresql
  username: rabhdev
  port: 5432
  host: localhost
  database: postgres
  password: 

test:
  encoding: unicode
  adapter: postgresql
  username: rabhtest
  port: 5432
  host: localhost
  database: postgres
  password: 

production:
  encoding: unicode
  adapter: postgresql
  username: 
  port: 5432
  host: 
  database: 
  password: 
  pool: 20


